# Scapy modification: use scapy-relative imports
from scapy.modules.crcmod.crcmod import *  # noqa: F401, F403
from scapy.modules.crcmod import predefined  # noqa: F401

# SCAPY MODIFICATION: add pre-defined names.
# for n in crcmod.predefined._crc_definitions_by_name.keys():
#   print("crc_{0} = predefined.mkCrcFun('{0}')".format(n))
crc_8 = predefined.mkCrcFun('8')
crc_8darc = predefined.mkCrcFun('8darc')
crc_8icode = predefined.mkCrcFun('8icode')
crc_8itu = predefined.mkCrcFun('8itu')
crc_8maxim = predefined.mkCrcFun('8maxim')
crc_8rohc = predefined.mkCrcFun('8rohc')
crc_8wcdma = predefined.mkCrcFun('8wcdma')
crc_16 = predefined.mkCrcFun('16')
crc_16buypass = predefined.mkCrcFun('16buypass')
crc_16dds110 = predefined.mkCrcFun('16dds110')
crc_16dect = predefined.mkCrcFun('16dect')
crc_16dnp = predefined.mkCrcFun('16dnp')
crc_16en13757 = predefined.mkCrcFun('16en13757')
crc_16genibus = predefined.mkCrcFun('16genibus')
crc_16maxim = predefined.mkCrcFun('16maxim')
crc_16mcrf4xx = predefined.mkCrcFun('16mcrf4xx')
crc_16riello = predefined.mkCrcFun('16riello')
crc_16t10dif = predefined.mkCrcFun('16t10dif')
crc_16teledisk = predefined.mkCrcFun('16teledisk')
crc_16usb = predefined.mkCrcFun('16usb')
crc_x25 = predefined.mkCrcFun('x25')
crc_xmodem = predefined.mkCrcFun('xmodem')
crc_modbus = predefined.mkCrcFun('modbus')
crc_kermit = predefined.mkCrcFun('kermit')
crc_ccittfalse = predefined.mkCrcFun('ccittfalse')
crc_augccitt = predefined.mkCrcFun('augccitt')
crc_24 = predefined.mkCrcFun('24')
crc_24flexraya = predefined.mkCrcFun('24flexraya')
crc_24flexrayb = predefined.mkCrcFun('24flexrayb')
crc_32 = predefined.mkCrcFun('32')
crc_32bzip2 = predefined.mkCrcFun('32bzip2')
crc_32c = predefined.mkCrcFun('32c')
crc_32d = predefined.mkCrcFun('32d')
crc_32mpeg = predefined.mkCrcFun('32mpeg')
crc_posix = predefined.mkCrcFun('posix')
crc_32q = predefined.mkCrcFun('32q')
crc_jamcrc = predefined.mkCrcFun('jamcrc')
crc_xfer = predefined.mkCrcFun('xfer')
crc_64 = predefined.mkCrcFun('64')
crc_64we = predefined.mkCrcFun('64we')
crc_64jones = predefined.mkCrcFun('64jones')
